name: Feature request
description: Suggest a legitimate new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: Feature description
    validations:
      required: true
